
#use the latest Unbuntu image for the container
FROM ubuntu:latest

#use the latest APT and upgrate for the software
#-y flag will answer yes for any install questions
RUN apt-get update && apt-get upgrade -y

#set command to echo "Hello, World!" when you first open it
CMD echo "Hello, World!"
